### ISSUE TITLE
很多码扫不出来 搞个锤子

### ISSUE THREAD

**Issue by Xxj-star** [EthanCo/QrCodeScanUI#1]

**Comment by EthanCo** [comment]
这只是个扫码UI框架，只用来显示扫码的UI，本身并不具备扫码功能，需要结合扫码解析库一起使用。

详见 : [Android 接入华为扫码库，实现堪比微信扫码的效果](https://blog.csdn.net/EthanCo/article/details/120027060)

**Comment by EthanCo** [comment]
本库出现的目的是
鉴于当前出现了微信扫码库、华为扫码统一服务 等 二维码解析库，且比原本的纯ZXing的二维码解析 识别率、识别速度有很明显的提升，所以有着将扫码库迁移到微信扫码库、华为扫码统一服务的需求，但是他们都是没有扫码UI的，故创建QrCodeScanUI，将 [BGAQRCode-Android ](https://github.com/bingoogolapple/BGAQRCode-Android)和[ZXingLite](https://github.com/jenly1314/ZXingLite) 中的扫码UI独立抽离取来，使其能独立使用，从而对接其他的扫码解析库。
